### ISSUE TITLE
Tern  Validator

### ISSUE THREAD

**Issue by angelozerr** [angelozerr/tern.java#260]
Today linters (validator for tern Lint, JSHInt, ESLInt, etc) https://github.com/angelozerr/tern.java/wiki/Tern-Linter are executed with :

 * with a custom tracker to  validate as user typing : https://github.com/angelozerr/tern.java/blob/master/eclipse/tern.eclipse.ide.ui/src/tern/eclipse/ide/internal/ui/validation/JavaEditorTracker.java
 * with a Builder : https://github.com/angelozerr/tern.java/blob/master/eclipse/tern.eclipse.ide.core/src/tern/eclipse/ide/internal/core/builder/TernBuilder.java

It should be better to remove those custom valudator with a WTP Validator (better UI to customize it)

**Comment by angelozerr** [comment]
@piotrtomiak I tell me if it's a good idea to transform TernBuilder to WTP Validator:

 * JSDT provide a JavaBuilder and not a WTP Validator.
 * Tern Validator has a complex files scope (IResourceProxyVisitor). I have not found how to use WTP Validator with a complex files scope? The HTML, XML WTP Validator doesn't manage custom files scope (custom IResourceProxyVisitor).

@piotrtomiak I'm not sure that it's a good idea to use WTP Validator for tern.

**Comment by piotrtomiak** [comment]
@angelozerr

> JSDT provides a JavaBuilder and not a WTP Validator. So why JSDT doesn't use WTP Validator?

Probably so that you can use JSDT without bringing any dependencies to the rest of WTP, or for other reasons. JSDT is a fork of JDT support, so maybe they didn't bother to unify with WTP validation framework. Anyway, it makes it harder for the users, so in MyEclipse we tend to put all the stuff into WTP validation framework, as we include that part of WTP anyway.

> Tern Validator has a complex files scope (IResourceProxyVisitor). I have not found how to use WTP Validator with a complex files scope? The HTML, XML WTP Validator doesn't manage custom files scope (custom IResourceProxyVisitor).

I am a bit lost. In TernBuilder I can see that you iterate over the script paths, but I don't see any IResourceProxyVisitor related code. The other thing I can see is that the incremental build is not handled at all, which means that you have to rebuild whole project to get lint updates.

The only problem I can see when using WTP Validator is to determine whether the JS file is on the script path. When validating resources during build, there is an object of class ValidationState passed, into which you can save some data, e.g. script path prefixes or something, which would allow to quickly determine whether the file is on the script path. Validator framework goes through all the files in the project anyway and your validator would be called only if the file matches the specified filter. Additionally the framework handles reconciliation validation through validate method with IValidationContext parameter. That would not require any filtering as I think that as-you-type validation should be performed even for the files not on the script path if they are edited.

**Comment by angelozerr** [comment]
> Probably so that you can use JSDT without bringing any dependencies to the rest of WTP, or for other reasons. JSDT is a fork of JDT support, 

Ok it's a good explanation.

> I am a bit lost. In TernBuilder I can see that you iterate over the script paths, but I don't see any IResourceProxyVisitor related code.

Ok sorry for my bad explanation. IResourceProxyVisitor is used for folder script path https://github.com/angelozerr/tern.java/blob/master/eclipse/tern.eclipse.ide.core/src/tern/eclipse/ide/internal/core/scriptpath/FolderScriptPath.java#L106 When you iterate from tern script path it excecutes custom IResourceProxyVisitor.

My question is which files are iterate by WTP Validator when a Build is executed? I have tried to use  WTP Validator V2 and executes a Build and I don't able to see file which are iterated. Perhaps I must NOT use Validator V2 (but simple Validator?)

> The only problem I can see when using WTP Validator is to determine whether the JS file is on the script path. 

I think we should provide a IDETernProject#IsInScope(IResource resource) method to manage that.

> That would not require any filtering as I think that as-you-type validation should be performed even for the files not on the script path if they are edited.

yes I agree with that.

I will try my test by using WTP Validator V1 (and not V2).

**Comment by piotrtomiak** [comment]
> My question is which files are iterate by WTP Validator when a Build is executed? I have tried to use WTP Validator V2 and executes a Build and I don't able to see file which are iterated. Perhaps I must NOT use Validator V2 (but simple Validator?)

AFAIK all the files in the project are iterated by V2 validator, but only those which are accepted by your validator are passed. So, if you make project -> clean all the eligible files for your validator will be validated. However, if you have incremental builds, only those which have been changed between builds. V1 validators are pretty slow, because you will have to scan resource tree yourself AFAIK, so I would go this way as a last resort.

ValBuilderJob.Visitor iterates over the files, either delta or whole project/resource. So, the iteration happens anyway if your user has WST validation builder in the project.

**Comment by angelozerr** [comment]
@piotrtomiak I have initialized WTP (V2) Tern Validator. See https://github.com/angelozerr/tern.java/commit/0cca73865e9953ed1090f262da123e09941f8bc8

Today it doesn't validate JS file, it displays in the console (Sys.err) trace in order to I understand how to the ValidationBuilder works.

I have added ValidationBuilder in my test project and I'm in "Build Automaticly" mode. Here the behaviour I understand : 

 * when Eclipse IDE starts, none validation are done (is it possible to execute the full build when IDE starts like TernBuilder?)
 * as soon as I change any file (js, xml, etc), TernValidator#validationStarting and TernValidtaor#validationFinishing
 * TernValidator#validate is called only for JS files (because I have added include rule in the extension point).
 * when I change a JS file the first time (or second time) TernValidator#validate is called only for the JS file which is updated. I expect that fullBuild was done for the first time.
 * the only mean to validat ethe full JS files, is when I execute Project -> Clean. My question is : is it possible to do a full build when project is opened or when the first JS file is updated (like TernBuilder).

Many thanks for your help.

**Comment by angelozerr** [comment]
@vrubezhny can you help me too please, thanks!

**Comment by piotrtomiak** [comment]
@angelozerr 

> when Eclipse IDE starts, none validation are done (is it possible to execute the full build when IDE starts like TernBuilder?)

And none validation should be done. All markers are persisted between sessions, so if the file is unchanged there is no reason to validate files again. This is very good as on large projects your IDE is very quickly ready to use. Imagine JDT recompiling all the files in your project on every start.

Why would you need a full build anyway?

> And there is a big problem with as-type-validator : org.eclipse.wst.sse.ui.sourcevalidation extension point seems working only with SSE Editor StructureEditor and JavaEditor doesn't extend it -(

That is a problem : ( Maybe there would be some way to overcome this. I'll look into this.

**Comment by angelozerr** [comment]
> Why would you need a full build anyway?

Ok thanks for your explanation, I agree with you.

> That is a problem

I'm afraid that it's not possible. I think a solution is to create a tracker like https://github.com/angelozerr/tern.java/blob/master/eclipse/tern.eclipse.ide.ui/src/tern/eclipse/ide/internal/ui/validation/JavaEditorTracker.java and create an instance of org.eclipse.wst.sse.ui.internal.reconcile.DocumentRegionProcessor here https://github.com/angelozerr/tern.java/blob/master/eclipse/tern.eclipse.ide.ui/src/tern/eclipse/ide/internal/ui/validation/JavaEditorTracker.java#L176

what do you think about this idea?

**Comment by piotrtomiak** [comment]
> what do you think about this idea?

Sounds like a very good idea. I had something like that in mind.

**Comment by angelozerr** [comment]
> Sounds like a very good idea. I had something like that in mind.

Cool:) Ok it was easy to implement this idea. Now when I can call WTP Source Validator https://github.com/angelozerr/tern.java/commit/e63b7715e5efb3fd0c3353414f7c9aa7df5abaaf#diff-b6a3f0e0d8204710b1ed68e01828dee9R20 as soon as I type JS code in the JSDT Editor.

It works too for HTML, JSP, etc. Next step is to implement those validator (I think it will easy).

After that I will work on an hard task IDETernproject#IsInScope(IResource resource) to check teh given resource is inside the validation scope (by using tern script path). I would like to integrate https://github.com/eclipsesource/jshint-eclipse/blob/master/bundles/com.eclipsesource.jshint.ui/src/com/eclipsesource/jshint/ui/internal/preferences/PathPattern.java to support complex path to include/exclude and use for instance .jshintignore to exclude some JS files. See https://github.com/angelozerr/tern.java/issues/150

**Comment by piotrtomiak** [comment]
> After that I will work on an hard task IDETernproject#IsInScope(IResource resource)

Nice :) I think it could be as simple as asking each TernScriptPath whether it has the resource. I would say that support for exclusions/inclusions is a separate task, not connected to validator, which can be done once we have validators working nicely (to not complicate this task). Each TernScriptPath object could internally check if the file matches any patterns. We depend on JSDT methods for that, like `org.eclipse.wst.jsdt.internal.compiler.util.Util.isExcluded`. It looks like the syntax for patterns is very similar (if not the same) to that of JSHint.

**Comment by angelozerr** [comment]
@piotrtomiak I have commited my work with WTP Tern Validator and it provides the 2 features : 

 * as you type validation 
 * global validation (Manual/Builder Validation)
 
 To activate Tern Validator, you must select one or several Tern Linter inside Project Properties Tern -> Modules (Lint, JSHint, ESLint, JSCS).
 
 There are 2 things which must be done : 
 
  * Line message (Tern Problem) : when you execute Manual/Builder Validation you can see inside Problem View a Line colomn which is equald every time to 0.
    I don't know for the moment how to manage that : I have the well start/end offset but I should compute line number with this information by using
    IDocument#getLineOfOffset(start) but I don't know how to get IDocument from a IFile, have you an idea?). 
  * IIDETernProject#isInScope(IResource resource) which returns every time true. I think in your case you will implement with JSDT Install Path. In my case
    I must implement it by using tern script path. I would like to support wildcard incude/exclude path to support bower.json exclude path, jshintignore, etc
    
  I will see that, but now I would like to support JSHint customization (for the moment it uses an hard coded config).
  
  Any feedback are welcome!

**Comment by piotrtomiak** [comment]
> Line message (Tern Problem) : when you execute Manual/Builder Validation you can see inside Problem View a Line colomn which is equald every time to 0. I don't know for the moment how to manage that : I have the well start/end offset but I should compute line number with this information by using IDocument#getLineOfOffset(start) but I don't know how to get IDocument from a IFile, have you an idea?).

Can you point me to the appropriate code, which should be doing this stuff? I have some ideas and could quickly point you to them. On the other hand you could request Tern server to return you line/line-pos pair instead of characters offsets.

> IIDETernProject#isInScope(IResource resource) which returns every time true. I think in your case you will implement with JSDT Install Path. In my case I must implement it by using tern script path. I would like to support wildcard incude/exclude path to support bower.json exclude path, jshintignore, etc

Thanks for info. Sounds perfect :)

Thank you, really great job! You are amazing :)

**Comment by angelozerr** [comment]
> Can you point me to the appropriate code

https://github.com/angelozerr/tern.java/blob/master/eclipse/linters/tern.eclipse.ide.linter.core/src/tern/eclipse/ide/linter/internal/core/validation/TernReporterCollector.java#L54

But I think we should modify some code because this helper is used for core and ui validation. I would like to avoid having JFace Text inside core.

> Thanks for info. Sounds perfect :)

Cool!

> Thank you, really great job! You are amazing :)

Wow, that's really cool:) Hope they will have not a lot of bugs...

**Comment by piotrtomiak** [comment]
Sorry for not replying so long, we are close to release. I will finally look into this on Monday most likely

**Comment by angelozerr** [comment]
> Sorry for not replying so long, we are close to release. I will finally look into this on Monday most likely

No problem, I understand. I'm working on JSON Editor by waiting for feedback about this issue.

**Comment by piotrtomiak** [comment]
Finally got the release out and I had a time to look into this. Additionally to offset and length, you should add:

message.setAttribute("charStart", start.intValue());
message.setAttribute("charEnd", end.intValue());

In some contexts those attributes are used and not offset or length.

There is no generic way to get an IDocument from IFile, since IDocuments are related to opened editors. However, you can get to IDocument for structured editors or IDocument for JSDT editor, in a non-UI context. Anyway, this is not a good idea, since marker based validation works with saved files and as-you-type validation works with IDocuments. So I think that line number has to be calculated on tern server side and passed through. This of course requires changes in all linters plugins and I am not that familiar with Tern-side API, so can't help with that :/

**Comment by angelozerr** [comment]
@piotrtomiak thank's for your information. I will study how to do that (for tern(lint, it will be easy but I don't know for other linter like JSHint).

**Comment by angelozerr** [comment]
I close this issue . I have created 2 issues : 

 * https://github.com/angelozerr/tern.java/issues/268 for line problem 
 * https://github.com/angelozerr/tern.java/issues/269 for isInscope implementation
