### ISSUE TITLE
Line message (Tern Problem)

### ISSUE THREAD

**Issue by angelozerr** [angelozerr/tern.java#268]
Line message (Tern Problem) : when you execute Manual/Builder Validation you can see inside Problem View a Line colomn which is equald every time to 0. I don't know for the moment how to manage that : I have the well start/end offset but I should compute line number with this information by using IDocument#getLineOfOffset(start) but I don't know how to get IDocument from a IFile, have you an idea?).

**Comment by angelozerr** [comment]
@piotrtomiak I have found a generic solution to retrieve the IDocument from a IFile if linter cannot support that. I will implement for tern-lint and JSHint if it is able to return lineNumber to avoid loading IDocument.

**Comment by piotrtomiak** [comment]
Really cool :) This code reminded me of some stuff I have found, when I was browsing through eclipse text search engine code. It might be worth looking whether they do dispose ad-hoc buffers, or use some other, lighter, solution there. I'll give it a look tomorrow.

**Comment by piotrtomiak** [comment]
The class I was speaking about is org.eclipse.search.internal.core.text.TextSearchVisitor (see processFiles(IFile[] files) ). It is trying to use an IDocument if possible, but if there is no active, it is just using binary contents of the file.

I can see two problems with creating a buffer for the file, if there is none existing:
- you are not disposing this buffer later on, so it probably stays and occupies memory; I would say that this is possibly a memory leak. 
- it is rather costly to create and initialize a document class.

I would say that for the case of just determining the line number, you could use binary file contents directly. The results could be cached in a WeakHashMap or something, which would allow the garbage collector to discard the cache if needed more memory. Here is a sketch of the algorithm:

1. Check cache for offsetMap, compare file timestamps and jump to 6 if data is present and not outdated
2. Open file stream for the file with FileReader or something else suitable
3. Scan the stream and calculate offsets for new lines (treat any of \r\n, \n, \r as line end)
4. Put offsets into TreeMap (offset -> line nr) (offset 0 maps to line 0 - always present)
5. Put the map into cache: weakCache.put(new String(file.toString()), offsetMap) [use new String(), so that key is immediately disposable]
6. Line no will be: offsetMap.floorEntry(offset).getValue()

TreeMap allows for binary search, which is O(log n), so pretty fast. FloorEntry method returns entry with the keyed offset equal or less than the offset we are querying, so I think this is exactly what we need.

**Comment by angelozerr** [comment]
@piotrtomiak thanks for your feedback.

tern-lint and tern-jshint supports now lineNumber. So it doesn't use IDocument.

I will try to do the same thing for ESLint and JSCS (when I will have time).

In other words only ESLint and JSCS uses IDocument.

The code which get IDocument from IFile comes from the Ant plugin. So I tell me that it should work. But it seems that it's not optimized according your comment. For dispose, I though that calling manager#disconnect https://github.com/angelozerr/tern.java/commit/60b2af7d3225c9c83f86f70febd42132b960216f#diff-7a2b28ab6c3de492941d924dd737dd37R169 manage that, no?

**Comment by piotrtomiak** [comment]
Right, that's correct. Missed that part. Cool, maybe that sophisticated part of code for detecting lines won't be required anyway.
