### ISSUE TITLE
Local jquery-1.11.0.min.js override Tern module jQuery

### ISSUE THREAD

**Issue by altukhov-a** [angelozerr/tern.java#293]
Hi! I use Tern 0.10.0
When convert my "Dynamic Web Project" to "Tern Project" my "WebContent" folder automatically add in Tern Script Path. After that I select jQuery module 
![jquery module](https://cloud.githubusercontent.com/assets/2371820/8252862/65bae4f2-1692-11e5-9e69-a11a16440925.png)
In my project I have local jquery script located in "WebContent/resource/js/jquery-1.11.0.min.js"
And when I press "Ctrl+Space" in code assistance I see references on my local jquery
![code assistance](https://cloud.githubusercontent.com/assets/2371820/8252976/bc2bf082-1693-11e5-87b1-9ff8518db98e.png)
"WebContent" disabled for delete from Tern Script Path
![script path](https://cloud.githubusercontent.com/assets/2371820/8252926/eb90d91a-1692-11e5-9918-e96afb74737b.png)
I cann't delete local script "WebContent/resource/js/jquery-1.11.0.min.js"
What can I do in this case?

**Comment by angelozerr** [comment]
I know this problem.

In short answer, please try to install 1.0.0-SNAPSHOT https://github.com/angelozerr/tern.java/wiki/Installation-Update-Site

This version provides a fix for https://github.com/marijnh/tern/issues/557 I think it's the same problem that you have. I suggest you that you install 1.0.0-SNAPSHOT an dgive me feedback.

> I cann't delete local script "WebContent/resource/js/jquery-1.11.0.min.js"

Yes I know this problem, I'm working on include/exclude tern script paths https://github.com/angelozerr/tern.java/issues/292 

Perhaps 1.0.0 will provide this feature.

**Comment by altukhov-a** [comment]
I update to http://oss.opensagres.fr/tern.repository/1.0.0-SNAPSHOT/, but it does not help me.
I get the same problem.
I revert to version 0.9.0 and it works for me.
Then another question. How can I add for example bootstap module into version 0.9.0?
Thank you!

**Comment by angelozerr** [comment]
> I revert to version 0.9.0 and it works for me.

That's really strange that 0.9.0 fix you rproblem?

To fix your problem, exclude tern script path must be implemented. I'm working on that.

> Then another question. How can I add for example bootstap module into version 0.9.0?

 * search in your ECLIPSE_HOME/plugins (of 0.10.0) a folder which starts with terns
 * copy folder ternjs*\node_modules\tern\node_modules\tern-bootstrap from 0.10.0 to 0.9.0
 * copy folder ternjs*\metadata\bootstrap.metadata.json from 0.10.0 to 0.9.0

For the image, it will not work, because it's 0.10.0 which gives teh capability to customize icon (stored in the metadata folder)

**Comment by altukhov-a** [comment]
I don't know why, but when I revert to 0.9.0
"WebContent" folder is not added in "Tern Script Path", accordingly local jquery script not override jquery module 
![script path 0 0 9](https://cloud.githubusercontent.com/assets/2371820/8256676/3225f662-16b1-11e5-9848-42b107e3d4c5.png)
Thank you very much, for help

**Comment by angelozerr** [comment]
Ok I understand more!

In 0.9.0, there were a bug which didn't use JSDT Install Path, it's the reason that your tern script path is empty.

In 0.10.0, JSDT Install Path is used (you can see (jsdt) label). Those tern script path cannot be deleted because they comes from JSDT Install Path. 

Exclude tern script path must definitely implemented. I'm working on this topic, but it's a long and hard task.

**Comment by altukhov-a** [comment]
Thanks again and good luck

**Comment by angelozerr** [comment]
@altukhov-a I have soon finished my work with include/exclude path. I will ping you when you will able to try and install 1.0.0-SNAPSHOT
