### ISSUE TITLE
Auto-completion is not including the declaring type

### ISSUE THREAD

**Issue by boniatillo-com** [angelozerr/tern.java#325]
In this image you can see the completion popup  shows the name of the members, but not the declaring type.

![image](https://cloud.githubusercontent.com/assets/12187299/9964922/ff1ae240-5e00-11e5-8659-9599e68e11ff.png)

It will be nice to see a popup like:

```
helloA() - A - pepe.js
helloB() - B - pepe.js
```

**Comment by angelozerr** [comment]
I'm afraid that it's not possible because ternjs doesn't provides this information (or we must create a PR to do that to support it).

@boniatillo-com you can see JSON request/response with Tern Console (to activate it go to Tern / Developmement and check "Trace on console") . With Tern console you will able what ternjs returns.

**Comment by boniatillo-com** [comment]
What is a PR?

I see tern has a "type" request to "query the type of something", and it works in Tern IDE when you hover an element. Maybe it can use that query to get the type of the var "b" and then show it in the proposals.

**Comment by angelozerr** [comment]
> What is a PR?

Pull Request. I mean do a contribution to ternjs.

> I see tern has a "type" request to "query the type of something", and it works in Tern IDE when you hover an element.

When you hover b variable, you can see that is B type but not when you hover helloB?

> "My solution" does not work because what we need is the declaring type, not the calling type.

To be honnest wiyh you, I have no time to investigate your proposition today, perhaps you should try to explain your wish to ternjs project?
