### ISSUE TITLE
Cache TernDocumentFile inside IDETernProject

### ISSUE THREAD

**Issue by angelozerr** [angelozerr/tern.java#394]
@piotrtomiak I would like to cache a TernDocumentFile  per opened editor inside the IDETernProject like I have done for typescript.java https://github.com/angelozerr/typescript.java/blob/master/core/ts.core/src/ts/resources/TypeScriptProject.java#L55

It will give us several advantage:

* don't create an instance of TernDocumentFile  each time (each time that completion, hyperlink is executed)
* gives the capability to know if a tern file is opened in an editor or not. It can be usefull for validation when you change the config, it revalidate project: 
    * if editor is opened (and not saved) it doesn't use the content of the editor but the content of the IFile. 
    * I have implemented quickfix for ESLint fix, and I get fix from the tern server eslint  only when you are typing (for performance). If validation config changes, fix is not loaded.

@piotrtomiak are you OK I cache TernDocumentFile   ?

**Comment by piotrtomiak** [comment]
@angelozerr The ITernFile was designed as a lightweight wrapper around File or IFile or IDocument with IFile. Cost of creation such object is very small and whole design bases on their short lifetime. I feel it's not a good idea to change that approach. If you need to add something, like an access to cached file or so, I would rather create an interface, like ITernFileInfo, which can give additional information you need, which implementation would be cached by TernFileManager e.g. and accessed by ITernFile.getAdaper(ITernFileInfo.class). ITernProject is not the best place to cache info related to ITernFile, as file objects themselves do not contain relation to tern project and it should be kept that way.

**Comment by angelozerr** [comment]
@piotrtomiak I don't want to cache the ITernFile. I would like just cache the opened JavaScript File (in other words TernDocumentFile). I tell me that we could do the same thing than TypeScript Service API which knows the opened ts file. I have done that for typescript.java nad I find it's a clean mean.

**Comment by piotrtomiak** [comment]
@angelozerr so, instead of creating the ad-hoc, you want to retrieve them using IDETernProject? I still feel that caching the TernDocumentFile objects is not a good idea. It seems straightforward, but there is always a big cost to handling cache, especially if you need to have it very accurate, as want to retrieve information about opened editors, etc. from it's state. So you need to start listening to BufferManager events, or editors opening closing to keep it up-to-date.

I think that providing an extra interface, which could be extended by a particular implementation of ITernFile will allow for low-level information access (i.e. tern.core - without IDETernProject part) and that interface would be responsible for extracting such information as whether the file is opened in an editor from an appropriate object which is responsible for storing such an information.

Interface:
```java
interface IExtTernFile {

   boolean isOpenedInEditor();
   String getFileContents();

}
```
Implementation
```java
public class TernDocumentFile extends ... implements IExtTernFile {

/* ...  */

public boolean isOpenedInEditor() {
   return Editors.isOpenedInEditor(document);
}

public String getFileContents() {
  return IOUtils.toString(iFile.getContents());
}

}
```
and usage:
```java
String contents;
if (ternFile instanceof IExtTernFile) {
  contents = ((IExtTernFile)ternFile).getFileContents();
} else {
  contents = ternFile.getContents();
}
```

**Comment by piotrtomiak** [comment]
What do you think?

**Comment by angelozerr** [comment]
> @angelozerr so, instead of creating the ad-hoc, you want to retrieve them using IDETernProject? 

Yes it was my idea.

>  So you need to start listening to BufferManager events, or editors opening closing to keep it up-to-date.

We have already done that:

 * here we open the TernDocumentFile https://github.com/angelozerr/tern.java/blob/master/eclipse/tern.eclipse.ide.ui/src/tern/eclipse/ide/internal/ui/EditorActivationTracker.java#L78

 * here we close the TernDocumentFile https://github.com/angelozerr/tern.java/blob/master/eclipse/tern.eclipse.ide.ui/src/tern/eclipse/ide/internal/ui/EditorActivationTracker.java#L116

```java
interface IExtTernFile {

   boolean isOpenedInEditor();
   String getFileContents();

}
```

> What do you think?

I don't know. I find it's shame to create an instance of TernDocumentFile just to know if file is opened in an editor.

**Comment by piotrtomiak** [comment]
> I don't know. I find it's shame to create an instance of TernDocumentFile just to know if file is opened in an editor.

Yes, intuitively creation of objects is pretty bad, but with Java I've learned to actually verify my intuition against how the language works. I've read some articles on creation of objects in java, can't find them now, but here are some links which also treat about object creation:

- http://programmers.stackexchange.com/questions/149563/should-we-avoid-object-creation-in-java
- http://stackoverflow.com/questions/401464/java-object-reuse

There are probably some good articles out there about the topic. So, my approach is that we shouldn't care about creation of ligthweight object - i.e. such which constructors just assign field values. Have a look at how costly is to retrieve an object from HashMap and it might turn out that you need much more instructions for that (It would be interesting to actually benchmark this ;) ). However, if object initialization is more complex, requiring some calculation etc., than yes, it is better to cache such objects.

**Comment by angelozerr** [comment]
The issue that I would like to fix is for Validate: 

 * you have typing some text in your editor
 * you do Validate.

The problem is that validate use ITernFile coming from IFile, so validation is done for IFile and not IDocument. A solution could save the whole editor before validating, but other WTP Validator doesn't work like this.

So when Validate is done (not by the UI, I mean as you type validation), we need to use TernDocumentFile or TernFile according fi editor is opened or not. The TernValidationHelper is in teh core, so we cannot use Editors.isOpenedInEditor(document); which belongs to UI and not Core.

If I cache the TernDocumentFile  inside IDETernProject,I can know easily if tern file is opened in an editor or not and in this case I can use the content of IDocument for validation. I don't know if you understand what I mean.

**Comment by piotrtomiak** [comment]
I've created a PR with proposed solution. Note that I haven't tested it much. Basically, instead of keeping our own cache of IDocuments, we can safely relay on the Text File Buffer Manager, which keeps track of opened IDocuments. The translation is done only if provided tern file does not provide IDocument adapter.

**Comment by piotrtomiak** [comment]
We could also go further and actually embed that behaviour in IDETernFile class, so that it automatically looks for IDocument if needed and takes contents from there, of course in a lazy manner.

**Comment by angelozerr** [comment]
> I've created a PR with proposed solution. 

Thanks!

> We could also go further and actually embed that behaviour in IDETernFile class

You mean set the code https://github.com/angelozerr/tern.java/pull/396/files#diff-1a94abe6b719114f91a97a2485952e19R64 and call ternFile.getAdapter(TernDocumentFile.class) to return if possible an instance of TernDocumentFile, is that?

**Comment by piotrtomiak** [comment]
> You mean set the code https://github.com/angelozerr/tern.java/pull/396/files#diff-1a94abe6b719114f91a97a2485952e19R64 and call ternFile.getAdapter(TernDocumentFile.class) to return if possible an instance of TernDocumentFile, is that?

Rather something like in the new PR I've created. The class is still lightweight, document is retrieved only if necessary. Since the class objects are short lived, we don't need to bother about refreshing contents of the document field, i.e. whether the document is still present in file buffers or not. Alternatively, we could access IDocument always through File buffers manager, but that depends on how costly it is.

As a result of the proposed change, Tern server will always be updated with unsaved contents from editors where possible. I think this is a radical, but a very good change. It helps with content assist accuracy, etc.

**Comment by angelozerr** [comment]
> As a result of the proposed change, Tern server will always be updated with unsaved contents from editors where possible. I think this is a radical, but a very good change. It helps with content assist accuracy, etc.

@piotrtomiak you convinced me to not cache tern file. Hope I have not lost your time with our discussion. Great PR, many thanks!

**Comment by piotrtomiak** [comment]
I wouldn't call that a lost time. I like the final solution :) I wouldn't actually get to it without all that discussion.

**Comment by angelozerr** [comment]
Ok I give up this issue.
